#!/usr/bin/env python3
"""SBOMs: the documents parse, and the search answers the question it exists for.

"Which of our images carry the vulnerable openssl" is asked under time pressure
by someone who cannot mount thirty images to find out. Two failures make that
question unanswerable while looking like it was answered:

  - a document that is not valid SPDX or CycloneDX. It is generated by awk, so
    the failure mode is a stray comma or an unescaped character, and it surfaces
    at the far end in somebody else's scanner rather than here.
  - a search that returns nothing because nothing has an SBOM, reported the same
    way as a search that returns nothing because nothing matched. Those mean
    opposite things and the second one is the dangerous one.

The generator itself is shell, so it is exercised as shell: the real
make-sbom.sh against a fake dpkg database.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

PROJ = tempfile.mkdtemp()
OUT = os.path.join(PROJ, "output")
os.makedirs(os.path.join(OUT, "bundles"), exist_ok=True)
os.environ.update(PROJECT_DIR=PROJ, STATIC_DIR="/tmp/none",
                  ADMIN_PASSWORD="ci-pw", SECRET_KEY="ci-secret")

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
from fastapi.testclient import TestClient   # noqa: E402
from app.main import app                    # noqa: E402

client = TestClient(app)
ok = fail = 0


def check(name, cond, extra=""):
    global ok, fail
    if cond:
        ok += 1
        print(f"  PASS  {name}")
    else:
        fail += 1
        print(f"  FAIL  {name} {extra}")


TOKEN = client.post("/api/auth/login",
                    data={"username": "admin", "password": "ci-pw"}).json()["access_token"]
AUTH = {"Authorization": f"Bearer {TOKEN}"}

MAKE_SBOM = os.path.join(HERE, "..", "..", "..", "builder", "make-sbom.sh")

print("== the generator produces documents that parse ==")
if not shutil.which("dpkg-query"):
    # On a machine without dpkg the generator cannot run at all, and pretending
    # otherwise would be a test that passes by not testing. Say so and use a
    # fixture for the rest, rather than skipping the search silently.
    print("  SKIP  no dpkg-query here; generator checks need a Debian-like host")
    generated = False
else:
    root = os.path.join(PROJ, "fakeroot")
    os.makedirs(os.path.join(root, "var", "lib", "dpkg"), exist_ok=True)
    # A dpkg database is a status file. Two installed packages, one that is
    # only `deinstall`ed (config files left behind, software gone) and must not
    # appear -- an SBOM naming software that is not there is worse than none.
    with open(os.path.join(root, "var", "lib", "dpkg", "status"), "w") as f:
        f.write(
            "Package: bash\nStatus: install ok installed\nArchitecture: amd64\n"
            "Version: 5.2.37-2\nDescription: shell\n\n"
            "Package: openssl\nStatus: install ok installed\nArchitecture: amd64\n"
            "Version: 3.5.1-1\nDescription: crypto\n\n"
            "Package: gone\nStatus: deinstall ok config-files\nArchitecture: amd64\n"
            "Version: 1.0-1\nDescription: removed\n\n")
    target = os.path.join(OUT, "test-image.img")
    open(target, "wb").write(b"not really an image")
    proc = subprocess.run(
        ["bash", MAKE_SBOM, "--root", root, "--out", target, "--name", "test-image",
         "--version", "2026.09.02-1200", "--distro", "debian", "--suite", "trixie",
         "--arch", "amd64"],
        capture_output=True, text=True)
    check("make-sbom.sh succeeds", proc.returncode == 0, proc.stderr[-400:])
    generated = proc.returncode == 0

    if generated:
        spdx = json.load(open(target + ".spdx.json"))
        cdx = json.load(open(target + ".cdx.json"))
        check("the SPDX document is valid JSON and says so",
              spdx["spdxVersion"] == "SPDX-2.3", spdx.get("spdxVersion"))
        check("the CycloneDX document likewise",
              cdx["bomFormat"] == "CycloneDX" and cdx["specVersion"] == "1.5", cdx.get("specVersion"))
        names = sorted(p["name"] for p in spdx["packages"])
        check("both installed packages are described", names == ["bash", "openssl"], names)
        check("a removed-but-config-files package is not",
              "gone" not in names, names)
        check("every SPDX package is related to the document",
              len(spdx["relationships"]) == len(spdx["packages"]),
              (len(spdx["relationships"]), len(spdx["packages"])))
        purls = sorted(c["purl"] for c in cdx["components"])
        check("purls name the distribution and the architecture",
              purls[0] == "pkg:deb/debian/bash@5.2.37-2?arch=amd64", purls[0])
        check("the image's own version is on the CycloneDX root component",
              cdx["metadata"]["component"]["version"] == "2026.09.02-1200",
              cdx["metadata"]["component"].get("version"))
        # The copy inside the image is what lets a running machine answer the
        # same question about itself, and what a bundle built from this image
        # carries along.
        check("the package list is left inside the root filesystem",
              os.path.isfile(os.path.join(root, "usr", "lib", "flipside", "packages.tsv")))

        print("== an empty database is refused rather than described as empty ==")
        bare = os.path.join(PROJ, "bareroot", "var", "lib", "dpkg")
        os.makedirs(bare, exist_ok=True)
        open(os.path.join(bare, "status"), "w").close()
        proc2 = subprocess.run(
            ["bash", MAKE_SBOM, "--root", os.path.dirname(os.path.dirname(bare)),
             "--out", os.path.join(OUT, "empty.img"), "--name", "empty"],
            capture_output=True, text=True)
        check("a root with no packages fails the SBOM rather than claiming none",
              proc2.returncode != 0, proc2.returncode)
        check("and does not leave a document behind saying the image is empty",
              not os.path.isfile(os.path.join(OUT, "empty.img.spdx.json")))

print("== the search finds a package across images and bundles ==")
# A fixture pair regardless of whether the generator ran, so the search is
# covered on any host.
open(os.path.join(OUT, "fixture-a.img"), "wb").write(b"stand-in for an image")
open(os.path.join(OUT, "bundles", "fixture-b.raucb"), "wb").write(b"hsqs")
with open(os.path.join(OUT, "fixture-a.img.packages.tsv"), "w") as f:
    f.write("bash\t5.2.37-2\tamd64\tbash\t5.2.37-2\n"
            "openssl\t3.0.11-1\tamd64\topenssl\t3.0.11-1\n")
with open(os.path.join(OUT, "bundles", "fixture-b.raucb.packages.tsv"), "w") as f:
    f.write("openssl\t3.5.1-1\tamd64\topenssl\t3.5.1-1\n"
            "libssl3\t3.5.1-1\tamd64\topenssl\t3.5.1-1\n")

r = client.get("/api/sbom", params={"package": "^openssl$"}, headers=AUTH).json()
found = sorted(x["artifact"] for x in r["results"])
# A superset, not an exact list: on a host with dpkg the generator section above
# has already written a third artifact that also contains openssl, and asserting
# equality would make this pass on a Mac and fail on the CI runner for a reason
# that has nothing to do with the search.
check("both fixture artifacts carrying openssl are named",
      {"fixture-a.img", "fixture-b.raucb"} <= set(found), found)
check("and nothing without openssl is",
      all("openssl" in [m["package"] for m in x["matches"]] for x in r["results"]),
      [(x["artifact"], x["matches"]) for x in r["results"]])
kinds = {x["artifact"]: x["kind"] for x in r["results"]}
check("bundles are distinguished from images",
      kinds.get("fixture-b.raucb") == "bundle", kinds)

r = client.get("/api/sbom", params={"package": "^openssl$", "version": "3.0."},
               headers=AUTH).json()
found = [x["artifact"] for x in r["results"]]
check("filtering by version narrows it to the vulnerable one",
      found == ["fixture-a.img"], found)

r = client.get("/api/sbom", params={"package": "ssl"}, headers=AUTH).json()
check("a substring pattern matches libssl3 too",
      any(m["package"] == "libssl3" for x in r["results"] for m in x["matches"]),
      r["results"])

print("== nothing-matched and nothing-to-match-against are distinguishable ==")
r = client.get("/api/sbom", params={"package": "^nosuchpackage$"}, headers=AUTH).json()
check("no matches is an empty result set", r["results"] == [], r["results"])
# The number searched is what separates it from a server with no SBOMs at all.
# Without it, an operator reading "no results" cannot tell whether their fleet
# is clear or whether nothing was ever checked.
check("but the number of artifacts searched is still reported",
      r["searched"] >= 2, r["searched"])

r = client.get("/api/sbom", params={"package": "["}, headers=AUTH)
check("a broken pattern is a 400, not a 500", r.status_code == 400, r.status_code)

print("== downloads are contained and honest about what is missing ==")
r = client.get("/api/sbom/fixture-a.img", params={"format": "spdx"}, headers=AUTH)
check("an artifact with no SPDX document says so, and which",
      r.status_code == 404 and "no SBOM" in r.text, r.status_code)
if generated:
    r = client.get("/api/sbom/test-image.img", params={"format": "spdx"}, headers=AUTH)
    check("a real one downloads", r.status_code == 200, r.status_code)
    check("as the registered SPDX media type",
          r.headers["content-type"].startswith("application/spdx+json"),
          r.headers.get("content-type"))
    r = client.get("/api/sbom/test-image.img", params={"format": "cyclonedx"}, headers=AUTH)
    check("and CycloneDX as its own",
          r.headers["content-type"].startswith("application/vnd.cyclonedx+json"),
          r.headers.get("content-type"))

# The name is joined onto a directory, so it is the usual containment question.
# Encoded forms on purpose: an unencoded ../ is collapsed by the client and by
# every proxy in front of this, so testing that form proves only that somebody
# else normalised it. The encoded one arrives at the endpoint intact, which is
# the case the endpoint has to survive on its own.
for hostile in ("..%2f..%2fetc%2fpasswd", "%2fetc%2fpasswd", ".hidden",
                "..%5c..%5cwindows"):
    r = client.get(f"/api/sbom/{hostile}", headers=AUTH)
    check(f"'{hostile}' is refused", r.status_code in (400, 404), r.status_code)

r = client.get("/api/sbom/fixture-a.img", params={"format": "passwd"}, headers=AUTH)
check("an unknown format is refused", r.status_code == 400, r.status_code)

print("== SBOMs are not public ==")
check("listing needs a credential", client.get("/api/sbom?package=x").status_code == 401)
check("downloading too", client.get("/api/sbom/fixture-a.img").status_code == 401)

print(f"\n{ok} passed, {fail} failed")
sys.exit(1 if fail else 0)
